ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER Chang
IDENTIFIED BY curso
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 100M ON USERS
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO Chang;

CONNECT Chang/curso
SHOW USER;

GRANT CONNECT TO Chang;

GRANT CREATE VIEW TO Chang;

